"""your_describe

Revision ID: 30566cf9883c
Revises: 
Create Date: 2021-07-28 17:55:01.109131

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '30566cf9883c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('City_DataBaseName',
    sa.Column('mID', sa.Integer(), nullable=False),
    sa.Column('dbname', sa.String(length=64), nullable=True),
    sa.Column('cityCode', sa.String(length=4), nullable=True),
    sa.Column('cityName', sa.String(length=32), nullable=True),
    sa.Column('cityPinYin', sa.String(length=32), nullable=True),
    sa.Column('generateDate', sa.Date(), nullable=True),
    sa.Column('index', sa.String(length=2), nullable=True),
    sa.Column('subPath', sa.String(length=128), nullable=True),
    sa.Column('otherInfo', sa.Text(), nullable=True),
    sa.Column('inDbTime', sa.DATETIME(), nullable=True),
    sa.Column('deviceType', sa.String(length=20), nullable=True),
    sa.Column('algConfPath', sa.String(length=128), nullable=True),
    sa.Column('photoPath', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('mID')
    )
    op.create_table('City_DataBaseName_WuPan',
    sa.Column('mID', sa.Integer(), nullable=False),
    sa.Column('dbname', sa.String(length=64), nullable=True),
    sa.Column('cityCode', sa.String(length=4), nullable=True),
    sa.Column('cityName', sa.String(length=32), nullable=True),
    sa.Column('cityPinYin', sa.String(length=32), nullable=True),
    sa.Column('generateDate', sa.Date(), nullable=True),
    sa.Column('index', sa.String(length=2), nullable=True),
    sa.Column('subPath', sa.String(length=128), nullable=True),
    sa.Column('otherInfo', sa.Text(), nullable=True),
    sa.Column('inDbTime', sa.DATETIME(), nullable=True),
    sa.Column('deviceType', sa.String(length=20), nullable=True),
    sa.Column('algConfPath', sa.String(length=128), nullable=True),
    sa.Column('photoPath', sa.String(length=128), nullable=True),
    sa.Column('packageName', sa.String(length=128), nullable=True),
    sa.Column('number', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('mID')
    )
    op.drop_table('city_databasename')
    op.drop_table('city_databasename_wupan')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city_databasename_wupan',
    sa.Column('mID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dbname', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('cityCode', mysql.VARCHAR(length=4), nullable=True),
    sa.Column('cityName', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('cityPinYin', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('generateDate', sa.DATE(), nullable=True),
    sa.Column('index', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('subPath', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('otherInfo', mysql.TEXT(), nullable=True),
    sa.Column('inDbTime', mysql.DATETIME(), nullable=True),
    sa.Column('deviceType', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('algConfPath', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('photoPath', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('packageName', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('number', mysql.VARCHAR(length=2), nullable=True),
    sa.PrimaryKeyConstraint('mID'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('city_databasename',
    sa.Column('mID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dbname', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('cityCode', mysql.VARCHAR(length=4), nullable=True),
    sa.Column('cityName', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('cityPinYin', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('generateDate', sa.DATE(), nullable=True),
    sa.Column('index', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('subPath', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('otherInfo', mysql.TEXT(), nullable=True),
    sa.Column('inDbTime', mysql.DATETIME(), nullable=True),
    sa.Column('deviceType', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('algConfPath', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('photoPath', mysql.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('mID'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('City_DataBaseName_WuPan')
    op.drop_table('City_DataBaseName')
    # ### end Alembic commands ###
